Comment.create!([
  {user_id: 8, ride_id: 149, comment_text: "Nice ride Lance!"},
  {user_id: 5, ride_id: 195, comment_text: "Sweet ride!"},
  {user_id: 5, ride_id: 191, comment_text: "11.13 miles no way!"},
  {user_id: 5, ride_id: 171, comment_text: "Great ride!"},
  {user_id: 7, ride_id: 183, comment_text: "Go Benny!!"},
  {user_id: 7, ride_id: 183, comment_text: "Go Benny!!"},
  {user_id: 7, ride_id: 182, comment_text: "Go Ben Go!"},
  {user_id: 6, ride_id: 134, comment_text: "Nice ride"},
  {user_id: 6, ride_id: 134, comment_text: "Nice ride"},
  {user_id: 6, ride_id: 184, comment_text: "6.3, go go go!"},
  {user_id: 5, ride_id: 170, comment_text: "Nice job tony!"},
  {user_id: 5, ride_id: 195, comment_text: "Why didn't you invite me guy??"},
  {user_id: 5, ride_id: 170, comment_text: "Tony! Tony!"},
  {user_id: 5, ride_id: 139, comment_text: "Go Tony Go!"},
  {user_id: 5, ride_id: 195, comment_text: "Cool!"},
  {user_id: 5, ride_id: 195, comment_text: "Cool ride!"},
  {user_id: 5, ride_id: 195, comment_text: "Awesome!"},
  {user_id: 5, ride_id: 195, comment_text: "Cool!"},
  {user_id: 5, ride_id: 195, comment_text: "Ride!"},
  {user_id: 5, ride_id: 183, comment_text: "Test!"},
  {user_id: 5, ride_id: 195, comment_text: "COMMENT"},
  {user_id: 5, ride_id: 195, comment_text: "Great!"},
  {user_id: 5, ride_id: 195, comment_text: "Comment!"},
  {user_id: 5, ride_id: 195, comment_text: "More comments!"},
  {user_id: 5, ride_id: 195, comment_text: "TEST"},
  {user_id: 5, ride_id: 195, comment_text: "Cool ride!"},
  {user_id: 5, ride_id: 192, comment_text: "Such a short ride LOL!"},
  {user_id: 5, ride_id: 193, comment_text: "Sweet!"},
  {user_id: 5, ride_id: 193, comment_text: "LOL"},
  {user_id: 5, ride_id: 193, comment_text: "LMAO"},
  {user_id: 5, ride_id: 193, comment_text: "HAHAH"},
  {user_id: 5, ride_id: 193, comment_text: "ROFL"},
  {user_id: 6, ride_id: 199, comment_text: "Sweet ride!"},
  {user_id: 6, ride_id: 199, comment_text: "You get tested lately LOL"},
  {user_id: 6, ride_id: 199, comment_text: "Great job!"},
  {user_id: 6, ride_id: 199, comment_text: "RIdes!!!"},
  {user_id: 8, ride_id: 197, comment_text: "11.77 Miles great job man!"},
  {user_id: 8, ride_id: 197, comment_text: "You really killed it!"},
  {user_id: 8, ride_id: 197, comment_text: "Unbelievable!"},
  {user_id: 8, ride_id: 197, comment_text: "So great!"},
  {user_id: 8, ride_id: 197, comment_text: "We gotta ride sometime!"},
  {user_id: 5, ride_id: 197, comment_text: "Let me come LOL"},
  {user_id: 5, ride_id: 164, comment_text: "Go Betty!"},
  {user_id: 5, ride_id: 137, comment_text: "Great job!"},
  {user_id: 5, ride_id: 173, comment_text: "No way!"},
  {user_id: 5, ride_id: 158, comment_text: "Crazy!"},
  {user_id: 5, ride_id: 197, comment_text: "Nice job!"},
  {user_id: 5, ride_id: 197, comment_text: "Nice!"},
  {user_id: 5, ride_id: 197, comment_text: "nice!"},
  {user_id: 5, ride_id: 168, comment_text: "Go Lance!"},
  {user_id: 5, ride_id: 196, comment_text: "Go Lance Go!!!!!"},
  {user_id: 5, ride_id: 215, comment_text: "One miles rides c'mon!"},
  {user_id: 6, ride_id: 217, comment_text: "35.7 miles WTF"},
  {user_id: 16, ride_id: 232, comment_text: "Cool!"},
  {user_id: 16, ride_id: 164, comment_text: "Great job Betty!"},
  {user_id: 16, ride_id: 234, comment_text: "Great app!"},
  {user_id: 5, ride_id: 236, comment_text: "What a beautiful day!"},
  {user_id: 8, ride_id: 236, comment_text: "8.1 > 1.4. LOL"},
  {user_id: 8, ride_id: 236, comment_text: "Can't stop won't stop"},
  {user_id: 18, ride_id: 237, comment_text: "I beat you Tony!!! HAHAHA"}
])
Friendship.create!([
  {user_id: 6, friend_id: 5},
  {user_id: 3, friend_id: 5},
  {user_id: 7, friend_id: 5},
  {user_id: 7, friend_id: 8},
  {user_id: 7, friend_id: 6},
  {user_id: 6, friend_id: 7},
  {user_id: 6, friend_id: 8},
  {user_id: 5, friend_id: 7},
  {user_id: 5, friend_id: 6},
  {user_id: 5, friend_id: 8},
  {user_id: 8, friend_id: 7},
  {user_id: 8, friend_id: 6},
  {user_id: 8, friend_id: 5},
  {user_id: 9, friend_id: 7},
  {user_id: 13, friend_id: 8},
  {user_id: 16, friend_id: 7},
  {user_id: 18, friend_id: 5},
  {user_id: 18, friend_id: 8},
  {user_id: 18, friend_id: 16},
  {user_id: 18, friend_id: 9}
])
Like.create!([
  {user_id: 8, ride_id: 149},
  {user_id: 5, ride_id: 193},
  {user_id: 5, ride_id: 149},
  {user_id: 5, ride_id: 195},
  {user_id: 6, ride_id: 164},
  {user_id: 6, ride_id: 164},
  {user_id: 6, ride_id: 199}
])
Ride.create!([
  {starting_location: "230 Central Park West, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.77, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "239 Central Park West, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.81, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "2307 Broadway, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.34, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "312 Columbus Avenue, New York, NY, United States", ending_location: "444 Columbus Avenue, New York, NY, United States", miles: 0.91, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "Madison Avenue, New York, NY, United States", miles: 0.31, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "443 West 56th Street, New York, NY, United States", miles: 2.64, in_progress: false, finished: true, user_id: 9, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "432 Amsterdam Avenue, New York, NY, United States", miles: 10.74, in_progress: false, finished: true, user_id: 13, top_five: false},
  {starting_location: "1502 3rd Avenue, New York, NY, United States", ending_location: "Times Square, Manhattan, NY, United States", miles: 2.79, in_progress: false, finished: true, user_id: 18, top_five: false},
  {starting_location: "Barclays Center, Atlantic Avenue, Brooklyn, NY, United States", ending_location: "times square", miles: 1000.0, in_progress: false, finished: true, user_id: 0, top_five: false},
  {starting_location: "1236 Madison Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 10.79, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "321 Amsterdam Avenue, New York, NY, United States", miles: 1.98, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "239 Central Park West, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.81, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "Time Warner Center, New York, NY, United States", ending_location: "Madison Avenue, New York, NY, United States", miles: 1.81, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1236 Madison Avenue, New York, NY, United States", ending_location: "321 Amsterdam Avenue, New York, NY, United States", miles: 3.22, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "321 Amsterdam Avenue, New York, NY, United States", miles: 1.98, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "Grand Central Terminal, East 42nd Street, New York, NY, United States", ending_location: "321 Amsterdam Avenue, New York, NY, United States", miles: 2.66, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "321 Amsterdam Avenue, New York, NY, United States", miles: 1.98, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "2315 Broadway, New York, NY, United States", ending_location: "333 Central Park West, New York, NY, United States", miles: 1.1, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "34246 Amsterdam Avenue, New York, NY, United States", ending_location: "1234 Lexington Avenue, New York, NY, United States", miles: 1.73, in_progress: false, finished: true, user_id: 10, top_five: false},
  {starting_location: "432 Amsterdam Avenue, New York, NY, United States", ending_location: "123", miles: 2.01, in_progress: false, finished: true, user_id: 13, top_five: false},
  {starting_location: "Prospect Park, Brooklyn, NY, United States", ending_location: "Bay Ridge, Brooklyn, NY, United States", miles: 4.58, in_progress: false, finished: true, user_id: 18, top_five: false},
  {starting_location: "230 Central Park West, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.77, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "Times Square, Manhattan, NY, United States", ending_location: "Effy's Kitchen, Lexington Avenue, New York, NY, United States", miles: 4.12, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "2341 Broadway, New York, NY, United States", ending_location: "449 Amsterdam Avenue, New York, NY, United States", miles: 0.44, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "321 Amsterdam Avenue, New York, NY, United States", miles: 1.98, in_progress: false, finished: true, user_id: 10, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "321 Amsterdam Avenue, New York, NY, United States", miles: 1.98, in_progress: false, finished: true, user_id: 11, top_five: false},
  {starting_location: "2318 Broadway, New York, NY, United States", ending_location: "333 Central Park West, New York, NY, United States", miles: 0.9, in_progress: false, finished: true, user_id: 14, top_five: false},
  {starting_location: "435 Amsterdam Avenue, New York, NY, United States", ending_location: "345 West 53rd Street, New York, NY, United States", miles: 1.64, in_progress: false, finished: true, user_id: 15, top_five: false},
  {starting_location: "432 Amsterdam Avenue, New York, NY, United States", ending_location: "22", miles: 0.2, in_progress: false, finished: true, user_id: 16, top_five: false},
  {starting_location: "Times Square, Manhattan, NY, United States", ending_location: "Highline Ballroom, West 16th Street, New York, NY, United States", miles: 2.07, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "321 Amsterdam Avenue, New York, NY, United States", ending_location: "1234 Lexington Avenue, New York, NY, United States", miles: 1.78, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "321 Amsterdam Avenue, New York, NY, United States", miles: 1.98, in_progress: false, finished: true, user_id: 12, top_five: false},
  {starting_location: "321 Amsterdam Avenue, New York, NY, United States", ending_location: "Rockefeller Plaza, New York, NY, United States", miles: 2.33, in_progress: false, finished: true, user_id: 14, top_five: false},
  {starting_location: "1236 Madison Avenue, New York, NY, United States", ending_location: "321 Amsterdam Avenue, New York, NY, United States", miles: 3.22, in_progress: false, finished: true, user_id: 15, top_five: false},
  {starting_location: "234 Central Park West, New York, NY, United States", ending_location: "432 Amsterdam Avenue, New York, NY, United States", miles: 0.66, in_progress: false, finished: true, user_id: 16, top_five: false},
  {starting_location: "321 Amsterdam Avenue, New York, NY, United States", ending_location: "328 8th Avenue, New York, NY, United States", miles: 1.4, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 9.5, in_progress: false, finished: true, user_id: 18, top_five: false},
  {starting_location: "Esanation, 9th Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 9.92, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "Brooklyn Bridge, New York, NY, United States", ending_location: "Essex Street, New York, NY, United States", miles: 1.39, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 9.5, in_progress: false, finished: true, user_id: 7, top_five: false},
  {starting_location: "2360 Broadway, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.5, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "230 Central Park West, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.77, in_progress: false, finished: true, user_id: 8, top_five: false},
  {starting_location: "230 Central Park West, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 2.6, in_progress: false, finished: true, user_id: 8, top_five: false},
  {starting_location: "Bronx County, NY, United States", ending_location: "Staten Island, NY, United States", miles: 29.34, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "2192 Broadway, New York, NY, United States", ending_location: "Times Square, Manhattan, NY, United States", miles: 2.2, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "1201 5th Avenue, New York, NY, United States", ending_location: "East 86th Street, New York, NY, United States", miles: 0.73, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "343 Amsterdam Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.15, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "Brooklyn, NY, United States", ending_location: "Bronx, NY, United States", miles: 17.78, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "Times Square, Manhattan, NY, United States", ending_location: "Madison Square Garden, Pennsylvania Plaza, New York, NY, United States", miles: 0.59, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "Times Square, Manhattan, NY, United States", ending_location: "Madison Square Garden, Pennsylvania Plaza, New York, NY, United States", miles: 0.59, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "Times Square, Manhattan, NY, United States", ending_location: "Madison Square Garden, Pennsylvania Plaza, New York, NY, United States", miles: 0.59, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "Times Square, Manhattan, NY, United States", ending_location: "Brooklyn Bridge, New York, NY, United States", miles: 4.81, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "Boston, MA, United States", ending_location: "New York, NY, United States", miles: 248.61, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 9.5, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "2139 Broadway, New York, NY, United States", ending_location: "Madison Avenue, New York, NY, United States", miles: 1.99, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "2307 Broadway, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.34, in_progress: false, finished: true, user_id: 7, top_five: false},
  {starting_location: "239 Central Park West, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.81, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "1201 5th Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 9.55, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "Effy's Cafe, West 96th Street, New York, NY, United States", miles: 1.68, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "230 73rd Street, Brooklyn, NY, United States", ending_location: "Madison Square Park, Madison Avenue, New York, NY, United States", miles: 10.08, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "2307 Broadway, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.34, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "2139 Broadway, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 10.96, in_progress: false, finished: true, user_id: 7, top_five: false},
  {starting_location: "1236 Madison Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 10.79, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "34246 Amsterdam Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.16, in_progress: false, finished: true, user_id: 8, top_five: false},
  {starting_location: "1236 Madison Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 10.79, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 9.5, in_progress: false, finished: true, user_id: 8, top_five: false},
  {starting_location: "2307 Broadway, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.34, in_progress: false, finished: true, user_id: 8, top_five: false},
  {starting_location: "2307 Broadway, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.34, in_progress: false, finished: true, user_id: 8, top_five: false},
  {starting_location: "239 Central Park West, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.81, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "2307 Broadway, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.34, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "201 Amsterdam Avenue, New York, NY, United States", ending_location: "Times Square, Manhattan, NY, United States", miles: 1.71, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "E.W.R., Brewster Road, Newark, NJ, United States", miles: 20.8, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "320 Central Park West, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 12.2, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "2360 Broadway, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 0.27, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "324 Columbus Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.21, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 9.5, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "2341 Broadway, New York, NY, United States", ending_location: "Awadh, Broadway, New York, NY, United States", miles: 0.65, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "213846 Broadway, New York, NY, United States", ending_location: "1234 Lexington Avenue, New York, NY, United States", miles: 1.86, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "234 Central Park West, New York, NY, United States", miles: 2.06, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "12", miles: 5.17, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "4321 Broadway, New York, NY, United States", miles: 6.3, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "4321 Broadway, New York, NY, United States", miles: 6.3, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "Brooklyn Bridge, New York, NY, United States", ending_location: "Atlantic Av - Barclays Ctr, Atlantic Avenue, NY, United Statesj", miles: 1.27, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 9.5, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "321 Amsterdam Avenue, New York, NY, United States", ending_location: "Bacaro, Division Street, New York, NY, United States", miles: 5.72, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 9.5, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "432 Amsterdam Avenue, New York, NY, United States", ending_location: "Times Square, Manhattan, NY, United States", miles: 2.26, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "FDR Drive, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 7.32, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "213846 Broadway, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.13, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "2341 Broadway, New York, NY, United States", ending_location: "Brooklyn, NY, United Statesj", miles: 0.57, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "Broken Land, Brooklyn, NY, United States", ending_location: "123", miles: 5.44, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "230 Central Park West, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.77, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "324 Columbus Avenue, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.21, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "230 Central Park West, New York, NY, United States", ending_location: "Brooklyn, NY, United States", miles: 11.77, in_progress: false, finished: true, user_id: 6, top_five: false},
  {starting_location: "123", ending_location: "333 Central Park West, New York, NY, United States", miles: 1.34, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "321 Amsterdam Avenue, New York, NY, United States", ending_location: "1245 Park Avenue, New York, NY, United States", miles: 2.19, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "123334 Melville Road, Farmingdale, NY, United States", miles: 35.7, in_progress: false, finished: true, user_id: 5, top_five: false},
  {starting_location: "1236 Madison Avenue, New York, NY, United States", ending_location: "320 Central Park West, New York, NY, United States", miles: 2.08, in_progress: false, finished: true, user_id: 15, top_five: false},
  {starting_location: "321 Amsterdam Avenue, New York, NY, United States", ending_location: "321", miles: 0.24, in_progress: false, finished: true, user_id: 16, top_five: false},
  {starting_location: "1234 Lexington Avenue, New York, NY, United States", ending_location: "230 Central Park West, New York, NY, United States", miles: 10.51, in_progress: false, finished: true, user_id: 16, top_five: false},
  {starting_location: "230 73rd St, Brooklyn, NY, United States", ending_location: "150 Broadway, Brooklyn, NY, United States", miles: 8.1, in_progress: false, finished: true, user_id: 8, top_five: false}
])
User.create!([
  {first_name: "Brian", last_name: "Griffin", email: "brian@email.com", miles: 3.23, profile_picture_url: nil, password_digest: "$2a$10$H0vkwd.tNVKwfocwjoYHp.6LERz/P42MyoVE7LE7GHjdp/lylr/Qu"},
  {first_name: "Kenny", last_name: "K", email: "kenny@email.com", miles: 6.94, profile_picture_url: nil, password_digest: "$2a$10$qFm3pICUneDQvVAGAkoopeu6r5slNEYJ4zjA9c/...adB8vMvyPn2"},
  {first_name: "Jon", last_name: "Eaves", email: "jon@email.com", miles: 11.61, profile_picture_url: nil, password_digest: "$2a$10$thT0iJRNLN5qK/4HPj4.tulE3w3yw4qASoUmfN.zx2fr/YRUU6una"},
  {first_name: "Benjamin", last_name: "Franklin", email: "ben@email.com", miles: 489.4, profile_picture_url: nil, password_digest: "$2a$10$ZiJ/X/RN5rcHE17sRb.fV.uPeZ56b8dGPTNh6vqJoztFzCqMOM3rK"},
  {first_name: "Tony", last_name: "Stark", email: "tony@email.com", miles: 65.81, profile_picture_url: nil, password_digest: "$2a$10$bcy/RTBdj3ZoYzP4J7B8BuzYDmDwfnDs3412X3EX4CW6bCZ11StkK"},
  {first_name: "Betty", last_name: "White", email: "betty@email.com", miles: 31.8, profile_picture_url: nil, password_digest: "$2a$10$4ehSblS14xIccP94agEk.OHRqshu0o4oJhMdxQ8ehl6OI6Wv.KFKi"},
  {first_name: "Sarah", last_name: "Wrigley", email: "sarah@email.com", miles: nil, profile_picture_url: nil, password_digest: "$2a$10$tjwiFh3w1NW463NPsRP40u5R1nzZLVPaTPaDNAsfNzM4r9x9UY7/G"},
  {first_name: "Lana", last_name: "Turner", email: "lana@email.com", miles: 16.87, profile_picture_url: nil, password_digest: "$2a$10$me57hLQ1C3.tT38YY1F9fOwEmA11T/KzQwKzKPLV1zmDI/5daeSM6"},
  {first_name: "Lance", last_name: "Armstrong", email: "lance@email.com", miles: 251.35, profile_picture_url: nil, password_digest: "$2a$10$ieKpzPQzhcefRSaDBV/7juSr.wrPrQlzpQ.pw.vQahTTZzWexSrAy"},
  {first_name: "Dan", last_name: "Hamburg", email: "dan@email.com", miles: 2.64, profile_picture_url: nil, password_digest: "$2a$10$zKIkZRkiW5YmSNKJEY83RO0qZhKE6Y7WbSP5KQodjsS3ajBN8geS."},
  {first_name: "Randy", last_name: "Marsh", email: "randy@email.com", miles: 3.71, profile_picture_url: nil, password_digest: "$2a$10$7aVS7sde3z5zdUkZRgd0S.ZLBDl7sEtqQDWSmE8y25rA90f193Ijq"},
  {first_name: "Homer", last_name: "Simpson", email: "homer@email.com", miles: 1.98, profile_picture_url: nil, password_digest: "$2a$10$QzGR.f/tlj46vbg//AMtVOOXvK8U3/.BF70rZEVptoAGdwDEKeyuy"},
  {first_name: "Stewie", last_name: "Griffin", email: "stewie@email.com", miles: 1.98, profile_picture_url: nil, password_digest: "$2a$10$zP/sHtIahFm7PboSQ2yo3.XKky6T/xdOawOX6MIDQgo9LxeJE7a1G"},
  {first_name: "Meg", last_name: "Griffin", email: "meg@email.com", miles: 12.75, profile_picture_url: nil, password_digest: "$2a$10$PNp8EBcWoWJ0YogNG1NdwuGeyEfBfqFhSDIlJHUgTJb0TNKfUf97m"}
])
